# Exercise 1



## Task A

In [2]:
import numpy as np

In [129]:
def standardize_matrix(A):
    mean_ = A.mean(axis=1)
    std_ = A.std(axis=1)
    return (A[:,:] - mean_[:,np.newaxis]) / std_[:, np.newaxis]

# creating an array of 100 lines,  D=10
M_random =4.*np.random.random((11, 3))+10.
M_standardized = standardize_matrix(M_random)
assert not(np.any( M_standardized.mean(axis=1)**2 > 1e-9)), "Found non-standardized"
assert not(np.any(( M_standardized.std(axis=1)-np.ones(M_standardized.shape[0]))**2 > 1e-9)), "Found non-standardized"
print(M_standardized)

[[ 0.31180922 -1.35050967  1.03870045]
 [-1.41421268  0.70573601  0.70847666]
 [-1.19763439  1.25016496 -0.05253057]
 [ 1.41404557 -0.68814586 -0.72589971]
 [-0.32607336  1.35478209 -1.02870873]
 [ 0.67264606  0.7410165  -1.41366256]
 [ 0.87275765 -1.40008032  0.52732267]
 [-1.00767781  1.36316368 -0.35548588]
 [-0.46432805 -0.92468497  1.38901302]
 [ 0.63403392  0.77774363 -1.41177755]
 [ 0.32742647 -1.35518037  1.0277539 ]]


## Task B, compute pairwise distances

In [125]:
def get_pairwise_distances(P, Q):
    assert P.shape[1]==2,""
    assert Q.shape[1]==2,""
    D = np.empty((P.shape[0], Q.shape[0]))
    for i in range(len(P)):
        for j in range(len(Q)):
            D[i,j] = np.sqrt(np.sum((P[i,:]-Q[j,:])**2))
    return D
def get_pairwise_distances_fast(P, Q):
    return np.sqrt(np.subtract.outer(P[:,0],Q[:,0])**2+np.subtract.outer(P[:,1],Q[:,1])**2)

def get_pairwise_distances_3(P, Q):
    return np.array([[np.linalg.norm(i-j) for i in Q] for j in P])
P = np.random.random((4, 2))
Q = np.random.random((9, 2))

In [126]:
#%%timeit
get_pairwise_distances(P, Q)

array([[0.5160676 , 0.75832508, 0.54710018, 0.7440712 , 1.00981184,
        0.95922104, 0.4077    , 0.64956112, 0.58362992],
       [0.10917801, 0.28128635, 0.24924088, 0.13261186, 0.79972815,
        0.93507968, 0.36595302, 0.51616153, 0.10206982],
       [0.31354804, 0.53737545, 0.42183803, 0.53788882, 0.97234151,
        0.98598518, 0.33871836, 0.60864471, 0.40955618],
       [0.72359134, 0.94102745, 0.48627458, 0.72698734, 0.13809474,
        0.39440653, 0.55703091, 0.30607567, 0.58965837]])

In [127]:
#%%timeit
get_pairwise_distances_fast(P,Q)

array([[0.5160676 , 0.75832508, 0.54710018, 0.7440712 , 1.00981184,
        0.95922104, 0.4077    , 0.64956112, 0.58362992],
       [0.10917801, 0.28128635, 0.24924088, 0.13261186, 0.79972815,
        0.93507968, 0.36595302, 0.51616153, 0.10206982],
       [0.31354804, 0.53737545, 0.42183803, 0.53788882, 0.97234151,
        0.98598518, 0.33871836, 0.60864471, 0.40955618],
       [0.72359134, 0.94102745, 0.48627458, 0.72698734, 0.13809474,
        0.39440653, 0.55703091, 0.30607567, 0.58965837]])

In [128]:
# %%timeit
get_pairwise_distances_3(P,Q)

array([[0.5160676 , 0.75832508, 0.54710018, 0.7440712 , 1.00981184,
        0.95922104, 0.4077    , 0.64956112, 0.58362992],
       [0.10917801, 0.28128635, 0.24924088, 0.13261186, 0.79972815,
        0.93507968, 0.36595302, 0.51616153, 0.10206982],
       [0.31354804, 0.53737545, 0.42183803, 0.53788882, 0.97234151,
        0.98598518, 0.33871836, 0.60864471, 0.40955618],
       [0.72359134, 0.94102745, 0.48627458, 0.72698734, 0.13809474,
        0.39440653, 0.55703091, 0.30607567, 0.58965837]])

## Task C

In [145]:
def get_p(X, mu, sigma):
    prefac = ( (2*np.pi)**(0.5*X.shape[0]) * np.linalg.det(sigma) )**(-1)
    shifted = X-mu
    exponent = -np.dot(0.5 * shifted.T, np.dot(np.linalg.inv(sigma), shifted))
    return prefac*np.exp(exponent)
def most_likely(X, theta1, theta2):
    p1 = get_p(X, *theta1)
    p2 = get_p(X, *theta2)
    print(p1, p2)

D = 3
most_likely(np.random.random(D), (np.zeros(D), np.eye(D)), (10, np.eye(D)))
    

0.039132107154543086 3.182187356537763e-61
